### ISSUE TITLE
WIP but ready

### ISSUE THREAD

**Issue by Fresheyeball** [aktowns/purescript-simple-dom#3]
I realize this is work in progress, but its also the most mature pure dom lib out there. Would you consider publishing this to bower?

**Comment by aktowns** [comment]
whilst theres still alot to be desired, i've tagged and registered with bower

**Comment by aktowns** [comment]
also managed to get a CI up and running for PR's and commits http://hades.avoidinspace.com:8080/github.com/aktowns/purescript-simple-dom/

**Comment by fluffynukeit** [comment]
I agree with @joneshf that purescript-dom is a misleading name.  You can't actually do anything to the dom with it.  I think modules that only expose foreign types should have "types" or "foreign types" in the name, e.g. purescript-dom-types.  This is similar to a fairly widely used convention in which a `.Types` module has only types.  It's so common, in fact, that when I *don't* see it, I expect the module to provide *some* kind of functionality.  This happened to me with purescript-dom.  So I disagree with @paf31 that the difference is merely cosmetic; what things are named does matter.

(Although, as an aside, @joneshf, I found purescript-events to have a misleading name as well since it has nothing to do with DOM events as far as I can tell :) )

A lot of JS UI frameworks are really useful, and to integrate them into PS using PS bindings, we need to have access to things like events (and more generally, effectful callbacks).  I've found that everything with PS is really easy and natural for the most part, but integrating with JS GUI libraries is hard because everyone is doing these things in a different way.

I don't have a solution, though.  Just a dude with an opinion and a keyboard...
